import './style.scss'
import '../node_modules/@fortawesome/fontawesome-free/js/all';
import '../node_modules/@fortawesome/fontawesome-free/scss/fontawesome.scss';
import '../node_modules/chart.js/dist/chart';
import './js/apiController.js';
import './js/ui.js';
import './js/media.js';
import './js/app.js';
import './js/carousel.js';
import './js/zingchart.js';
import './js/slider.js';
import './js/main.js';
import './js/player.js';